
language: php

notifications:
  email:
    recipients:
    - kennethhendricks@catalyst-au.net

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.6

addons:
  postgresql: "9.3"

env:
  - DB=pgsql MOODLE_BRANCH=MOODLE_27_STABLE_FSAPI MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
  - DB=mysqli MOODLE_BRANCH=MOODLE_27_STABLE_FSAPI MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
  - DB=pgsql MOODLE_BRANCH=MOODLE_28_STABLE_FSAPI MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
  - DB=mysqli MOODLE_BRANCH=MOODLE_28_STABLE_FSAPI MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
  - DB=pgsql MOODLE_BRANCH=MOODLE_29_STABLE_FSAPI MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
  - DB=mysqli MOODLE_BRANCH=MOODLE_29_STABLE_FSAPI MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
  - DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE_FSAPI MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
  - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE_FSAPI MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE_FSAPI MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
  - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE_FSAPI MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE_FSAPI MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
  - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE_FSAPI MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
  - DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=master

matrix:
  include:
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE_FSAPI MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE_FSAPI MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE_FSAPI MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE_FSAPI MOODLE_REPO=https://github.com/kenneth-hendricks/moodle-fs-api.git
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=master
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci add-plugin catalyst/moodle-local_aws
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
# - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
# - moodle-plugin-ci csslint    # No CSS
  - moodle-plugin-ci shifter
# - moodle-plugin-ci jshint     # No JS
  - moodle-plugin-ci phpunit
# - moodle-plugin-ci behat      # No tests yet
